language: node_js
node_js: lts/*
os: osx
osx_image: xcode9.1
env:
  global:
  - APP_NAME=electron-next-boilerplate
  - CSC_IDENTITY_AUTO_DISCOVERY=false
before_install:
  - brew update
install:
  - yarn install
before_script:
  - sudo Xvfb :99 -ac -screen 0 1920x1080x8 &
  - sleep 3
script:
  - yarn test --coverage
before_deploy:
  - yarn dist -mwl
  - cd dist/win-unpacked && zip -9 -ry ${APP_NAME}-win-x64.zip . && cd ../..
  - cd dist/mac && zip -9 -ry ${APP_NAME}-mac-x64.zip . && cd ../..
  - cd dist/linux-unpacked && zip -9 -ry ${APP_NAME}-linux-x64.zip . && cd ../..
deploy:
  provider: releases
  api_key:
    secure: PoJB0NBoiaH2iTKnm+c4Zg6qdt+2J8ydh3crrAGLUgCNA6u3HO/fH7I1W2+IuXeOguKfQU0kXOhfWc20hHmK8vWPm/IQozect1wwUVSmg+c04W5sIT9o+t+9RMewz1xhYI0goFWShI8Xtlhpurn9Fjwd1O+f1Mz3q2PQNsUcGBjCqIJVWcIMXdWmOnvWj6mC0HV/13SfXLvaT+V7cp5NS0ylLL/tLB4UaY6jI80yK3UpMCo4XnJNO4FMe9UGaLU3shMuVcB2eK4JI/CI642fS8fIOv5L+Vqw2cpVq0F6k1ENf47/B+KUT0NNZNFUQB16bDJBpzLFuTV9nj+5mv+THgoy2DV1WslVIbguJonipgX7QaRnxNS+YZdmScykD6rynVA70GlH0NxgRhhNXMdWb8sw27wbRKyXnAnyIZtRYIFGFkfz7xoFeO+EFqpOoOzmvHrhj+e8qhhCrqCXe6iKkFKFFjpf6PJ3EBMLg+YSo3PY/QBxq6A8L4I7QJFg41hqLeu9oeH5ZCn3s9aUuuP7eDdHHnsVTc4PEltnpoYXVw/3c833Q6TvKPDDqTp7sfm6YExQ8XrfGX1mG+tMtxcIp6fVxKzeTEesI5sAzbhP1iGz22BDCDB39/08i4OECTqXo6UMjdo4EMPk29oAMKsjRN3zsq/ygThKXUmTObuP/+s=
  file:
    - dist/win-unpacked/${APP_NAME}-win-x64.zip
    - dist/mac/${APP_NAME}-mac-x64.zip
    - dist/linux-unpacked/${APP_NAME}-linux-x64.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master